#!/usr/bin/python

import RPi.GPIO as GPIO
import time

import binascii


def text_to_bits(text, encoding='utf-8', errors='surrogatepass'):
    bits = bin(int(binascii.hexlify(text.encode(encoding, errors)), 16))[2:]
    return bits.zfill(8 * ((len(bits) + 7) // 8))


value = "t"

GPIO.setmode(GPIO.BCM)

GPIO.setup(23, GPIO.OUT)
GPIO.setup(24, GPIO.OUT)

value_bit = text_to_bits(value)

print "t"
print value_bit

for x in range(0,4):
	GPIO.output(23, GPIO.HIGH)
	time.sleep(1)

for x in range(0,8):
	if value_bit[x] == "0" :		
		print value_bit[x]
		GPIO.output(23, GPIO.LOW)
		time.sleep(1)
	
	if value_bit[x] == "1" :
		print value_bit[x]
		GPIO.output(23, GPIO.HIGH)
		time.sleep(1)
		GPIO.output(23, GPIO.LOW)